# Generated by Django 5.2.15 on 2026-07-10 17:39

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=accounts.models.get_random_card_number, editable=False, max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], default='DEBIT', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
        ),
    ]
