# Generated by Django 5.2.15 on 2026-07-11 02:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(default=accounts.models.get_random_cvv, max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=accounts.models.get_default_expiry),
        ),
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='card',
            name='transaction_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
